/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto_swing.presentacion;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import proyecto_swing.excepciones.MatriculaInvalidaException;
import proyecto_swing.excepciones.NotaException;
import proyecto_swing.modelo.Calificaciones;
import proyecto_swing.modelo.Curso;
import proyecto_swing.modelo.Estudiante;

import proyecto_swing.negocio.CalificacionNegocio;
import proyecto_swing.negocio.CursoNegocio;
import proyecto_swing.negocio.EstudianteNegocio;

/**
 *
 * @author Anyel
 */
public class CalificacionPanel extends javax.swing.JPanel {

    private CalificacionNegocio calificacionNegocio;
    private EstudianteNegocio estudianteNegocio;
    private CursoNegocio cursoNegocio;

    private boolean modoEdicion = false;

    /**
     * Creates new form CalificacionPanel
     */
    public CalificacionPanel() {
        initComponents();
        calificacionNegocio = new CalificacionNegocio();
        estudianteNegocio = new EstudianteNegocio();
        cursoNegocio = new CursoNegocio();

        cargarCombos();
        cargarTabla();
    }

    private void cargarCombos() {

        cmbEstudiante.removeAllItems();

        for (Estudiante e : estudianteNegocio.obtenerTodos()) {

            if (e.isActivo()) {

                cmbEstudiante.addItem(
                        e.getId()
                        + " - "
                        + e.getNombre()
                );
            }
        }

        cmbCurso.removeAllItems();

        for (Curso c : cursoNegocio.obtenerTodos()) {

            if (c.isActivo()) {

                cmbCurso.addItem(
                        c.getId()
                        + " - "
                        + c.getNombre()
                );
            }
        }
    }

    private void cargarTabla() {
        llenarTabla(calificacionNegocio.obtenerTodas());
    }

    private void llenarTabla(java.util.List<Calificaciones> lista) {

        DefaultTableModel modelo
                = (DefaultTableModel) tblCalificaciones.getModel();

        modelo.setRowCount(0);

        for (Calificaciones c : lista) {

            modelo.addRow(new Object[]{
                c.getId(),
                c.getEstudiante().getNombre(),
                c.getCurso().getNombre(),
                c.getNota(),
                c.getEstado(),
                c.getObservacion()
            });
        }
    }

    private void limpiarCampos() {

        txtId.setText("");
        txtNota.setText("");
        txtObservacion.setText("");

        if (cmbEstudiante.getItemCount() > 0) {
            cmbEstudiante.setSelectedIndex(0);
        }

        if (cmbCurso.getItemCount() > 0) {
            cmbCurso.setSelectedIndex(0);
        }

        modoEdicion = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnBuscarEstudiante = new javax.swing.JButton();
        btnBuscarCurso = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnOrdenarNota = new javax.swing.JButton();
        btnPromedios = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCalificaciones = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblNota = new javax.swing.JLabel();
        lblObservacion = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNota = new javax.swing.JTextField();
        txtBuscarEstudiante = new javax.swing.JTextField();
        txtBuscarCurso = new javax.swing.JTextField();
        cmbEstudiante = new javax.swing.JComboBox<>();
        cmbCurso = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(224, 223, 183));

        btnLimpiar.setBackground(new java.awt.Color(242, 241, 174));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnBuscarEstudiante.setBackground(new java.awt.Color(255, 255, 204));
        btnBuscarEstudiante.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        btnBuscarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/magnifier-1_icon-icons.com_56924.png"))); // NOI18N
        btnBuscarEstudiante.setText("Buscar Estudiante");
        btnBuscarEstudiante.addActionListener(this::btnBuscarEstudianteActionPerformed);

        btnBuscarCurso.setBackground(new java.awt.Color(255, 255, 204));
        btnBuscarCurso.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        btnBuscarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/magnifier-1_icon-icons.com_56924.png"))); // NOI18N
        btnBuscarCurso.setText("Buscar Curso");
        btnBuscarCurso.addActionListener(this::btnBuscarCursoActionPerformed);

        btnRefrescar.setBackground(new java.awt.Color(255, 255, 204));
        btnRefrescar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/-autorenew_90718.png"))); // NOI18N
        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(this::btnRefrescarActionPerformed);

        btnOrdenarNota.setBackground(new java.awt.Color(255, 255, 204));
        btnOrdenarNota.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        btnOrdenarNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/filtering_icon_246394.png"))); // NOI18N
        btnOrdenarNota.setText("Ordenar por Nota");
        btnOrdenarNota.addActionListener(this::btnOrdenarNotaActionPerformed);

        btnPromedios.setBackground(new java.awt.Color(255, 255, 204));
        btnPromedios.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        btnPromedios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3844476-eye-see-show-view-watch_110339.png"))); // NOI18N
        btnPromedios.setText("Ver Promedios");
        btnPromedios.addActionListener(this::btnPromediosActionPerformed);

        btnHistorial.setBackground(new java.awt.Color(255, 255, 204));
        btnHistorial.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3643772-archive-archives-document-folder-open_113445.png"))); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.addActionListener(this::btnHistorialActionPerformed);

        tblCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Estudiante", "Curso", "Nota", "Estado", "Observación"
            }
        ));
        jScrollPane1.setViewportView(tblCalificaciones);

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(13, 78, 111));
        lblTitulo.setText("Calificaciones");

        lblId.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(28, 84, 112));
        lblId.setText("ID Calificación:");

        lblEstudiante.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        lblEstudiante.setForeground(new java.awt.Color(20, 73, 100));
        lblEstudiante.setText("Estudiante:");

        lblCurso.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(24, 88, 119));
        lblCurso.setText("Curso:");

        lblNota.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        lblNota.setForeground(new java.awt.Color(21, 87, 119));
        lblNota.setText("Nota (0-100):");

        lblObservacion.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        lblObservacion.setForeground(new java.awt.Color(14, 82, 117));
        lblObservacion.setText("Observación:");

        cmbEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtObservacion.setColumns(20);
        txtObservacion.setRows(3);
        jScrollPane2.setViewportView(txtObservacion);

        btnGuardar.setBackground(new java.awt.Color(236, 233, 176));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnEditar.setBackground(new java.awt.Color(242, 241, 166));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editra.png"))); // NOI18N
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(242, 241, 188));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash_bin_icon-icons.com_67981.png"))); // NOI18N
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurso)
                            .addComponent(lblNota)
                            .addComponent(lblEstudiante)
                            .addComponent(lblId)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblObservacion)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOrdenarNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRefrescar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPromedios, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstudiante))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCurso)
                            .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNota)
                            .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblObservacion)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuardar)
                                    .addComponent(btnEditar)
                                    .addComponent(btnEliminar)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOrdenarNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRefrescar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPromedios, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarEstudiante)
                            .addComponent(btnBuscarCurso))
                        .addGap(61, 61, 61))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {

            int id = Integer.parseInt(txtId.getText().trim());

            double nota = Double.parseDouble(txtNota.getText().trim());

            int indiceEstudiante = cmbEstudiante.getSelectedIndex();
            int indiceCurso = cmbCurso.getSelectedIndex();

            if (indiceEstudiante == -1 || indiceCurso == -1) {

                JOptionPane.showMessageDialog(
                        this,
                        "Debe seleccionar estudiante y curso."
                );

                return;
            }

            Estudiante estudiante
                    = estudianteNegocio.obtenerTodos()
                            .get(indiceEstudiante);

            Curso curso
                    = cursoNegocio.obtenerTodos()
                            .get(indiceCurso);

            Calificaciones calificacion = new Calificaciones(
                    id,
                    estudiante,
                    curso,
                    nota,
                    txtObservacion.getText().trim()
            );

            if (modoEdicion) {

                calificacionNegocio.editar(calificacion);

                JOptionPane.showMessageDialog(
                        this,
                        "Calificación actualizada correctamente."
                );

            } else {

                calificacionNegocio.registrar(calificacion);

                JOptionPane.showMessageDialog(
                        this,
                        "Calificación registrada correctamente."
                );
            }

            limpiarCampos();
            cargarTabla();

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    "El ID y la nota deben ser valores numéricos."
            );

        } catch (NotaException | MatriculaInvalidaException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int fila = tblCalificaciones.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una calificación de la tabla."
            );

            return;
        }

        Calificaciones calificacion
                = calificacionNegocio.obtenerTodas().get(fila);

        txtId.setText(String.valueOf(calificacion.getId()));
        txtNota.setText(String.valueOf(calificacion.getNota()));
        txtObservacion.setText(calificacion.getObservacion());

        for (int i = 0; i < cmbEstudiante.getItemCount(); i++) {

            if (cmbEstudiante.getItemAt(i)
                    .startsWith(calificacion.getEstudiante().getId() + " - ")) {

                cmbEstudiante.setSelectedIndex(i);
                break;
            }
        }

        for (int i = 0; i < cmbCurso.getItemCount(); i++) {

            if (cmbCurso.getItemAt(i)
                    .startsWith(calificacion.getCurso().getId() + " - ")) {

                cmbCurso.setSelectedIndex(i);
                break;
            }
        }

        modoEdicion = true;
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tblCalificaciones.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una calificación para eliminar."
            );

            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea eliminar esta calificación?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {

            Calificaciones calificacion
                    = calificacionNegocio.obtenerTodas().get(fila);

            calificacionNegocio.eliminar(calificacion.getId());

            JOptionPane.showMessageDialog(
                    this,
                    "Calificación eliminada."
            );

            limpiarCampos();
            cargarTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
        // TODO add your handling code here:
        llenarTabla(
                calificacionNegocio.buscarPorEstudiante(
                        txtBuscarEstudiante.getText().trim()
                )
        );
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed

    private void btnBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCursoActionPerformed
        // TODO add your handling code here:
        llenarTabla(
                calificacionNegocio.buscarPorCurso(
                        txtBuscarCurso.getText().trim()
                )
        );
    }//GEN-LAST:event_btnBuscarCursoActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
        txtBuscarEstudiante.setText("");
        txtBuscarCurso.setText("");

        cargarCombos();
        cargarTabla();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnOrdenarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarNotaActionPerformed
        // TODO add your handling code here:
        llenarTabla(calificacionNegocio.ordenarPorNota());
    }//GEN-LAST:event_btnOrdenarNotaActionPerformed

    private void btnPromediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromediosActionPerformed
        // TODO add your handling code here:
        StringBuilder texto = new StringBuilder();

        texto.append("Promedios por curso:\n");

        for (java.util.Map.Entry<String, Double> entrada
                : calificacionNegocio.obtenerPromediosPorCurso().entrySet()) {

            texto.append("  ")
                    .append(entrada.getKey())
                    .append(": ")
                    .append(String.format("%.2f", entrada.getValue()))
                    .append("\n");
        }

        texto.append("\nPromedios por estudiante:\n");

        for (java.util.Map.Entry<String, Double> entrada
                : calificacionNegocio.obtenerPromediosPorEstudiante().entrySet()) {

            texto.append("  ")
                    .append(entrada.getKey())
                    .append(": ")
                    .append(String.format("%.2f", entrada.getValue()))
                    .append("\n");
        }

        JOptionPane.showMessageDialog(
                this,
                texto.toString(),
                "Promedios",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnPromediosActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        StringBuilder historial = new StringBuilder();

        for (String accion : calificacionNegocio.getHistorial()) {

            historial.append(accion)
                    .append("\n");
        }

        JOptionPane.showMessageDialog(
                this,
                historial.toString(),
                "Historial",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void tblCalificacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCalificacionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCalificacionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnOrdenarNota;
    private javax.swing.JButton btnPromedios;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JComboBox<String> cmbEstudiante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblObservacion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblCalificaciones;
    private javax.swing.JTextField txtBuscarCurso;
    private javax.swing.JTextField txtBuscarEstudiante;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextArea txtObservacion;
    // End of variables declaration//GEN-END:variables
}
