/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto_swing.presentacion;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import proyecto_swing.modelo.Curso;
import proyecto_swing.modelo.Estudiante;
import proyecto_swing.modelo.Matricula;

import proyecto_swing.negocio.CursoNegocio;
import proyecto_swing.negocio.EstudianteNegocio;
import proyecto_swing.negocio.MatriculaNegocio;

/**
 *
 * @author PC
 */
public class MatriculaPanel extends javax.swing.JPanel {

    private MatriculaNegocio matriculaNegocio;
    private EstudianteNegocio estudianteNegocio;
    private CursoNegocio cursoNegocio;

    /**
     * Creates new form MatriculaPanel
     */
    public MatriculaPanel() {
        initComponents();
        matriculaNegocio = new MatriculaNegocio();
        estudianteNegocio = new EstudianteNegocio();
        cursoNegocio = new CursoNegocio();

        cargarCombos();
        cargarTabla();
    }

    private void cargarCombos() {

        cmbEstudiante.removeAllItems();

        for (Estudiante e : estudianteNegocio.obtenerTodos()) {

            if (e.isActivo()) {

                cmbEstudiante.addItem(
                        e.getId()
                        + " - "
                        + e.getNombre()
                );
            }
        }

        cmbCurso.removeAllItems();

        for (Curso c : cursoNegocio.obtenerTodos()) {

            if (c.isActivo()) {

                cmbCurso.addItem(
                        c.getId()
                        + " - "
                        + c.getNombre()
                );
            }
        }
    }

    private void cargarTabla() {

        DefaultTableModel modelo
                = (DefaultTableModel) tblMatriculas.getModel();

        modelo.setRowCount(0);

        for (Matricula m : matriculaNegocio.obtenerTodas()) {

            modelo.addRow(new Object[]{
                m.getId(),
                m.getEstudiante().getNombre(),
                m.getCurso().getNombre()

            });
        }
    }

    private void limpiarCampos() {

        txtId.setText("");

        txtBuscarEstudiante.setText("");

        txtBuscarCurso.setText("");

        if (cmbEstudiante.getItemCount() > 0) {

            cmbEstudiante.setSelectedIndex(0);

        }

        if (cmbCurso.getItemCount() > 0) {

            cmbCurso.setSelectedIndex(0);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblBuscarEstudiante = new javax.swing.JLabel();
        lblBuscarCurso = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtBuscarEstudiante = new javax.swing.JTextField();
        txtBuscarCurso = new javax.swing.JTextField();
        cmbEstudiante = new javax.swing.JComboBox<>();
        cmbCurso = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscarEstudiante = new javax.swing.JButton();
        btnBuscarCurso = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatriculas = new javax.swing.JTable();

        lblTitulo.setText("Matricula");

        lblId.setText("ID Matricula");

        lblEstudiante.setText("Estudiante:");

        lblCurso.setText("Curso:");

        lblBuscarEstudiante.setText("Buscar Estudiante:");

        lblBuscarCurso.setText("Buscar Curso:");

        cmbEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnBuscarEstudiante.setText("Buscar Estudiante");
        btnBuscarEstudiante.addActionListener(this::btnBuscarEstudianteActionPerformed);

        btnBuscarCurso.setText("Buscar Curso");
        btnBuscarCurso.addActionListener(this::btnBuscarCursoActionPerformed);

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(this::btnRefrescarActionPerformed);

        btnHistorial.setText("Historial");
        btnHistorial.addActionListener(this::btnHistorialActionPerformed);

        tblMatriculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Estudiante", "Curso"
            }
        ));
        jScrollPane1.setViewportView(tblMatriculas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCurso)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId)
                                    .addComponent(lblEstudiante))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtId)
                                    .addComponent(cmbEstudiante, 0, 120, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefrescar)
                        .addGap(18, 18, 18)
                        .addComponent(btnHistorial))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBuscarEstudiante)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarEstudiante))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBuscarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCurso)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstudiante)
                    .addComponent(cmbEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurso)
                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnRefrescar)
                    .addComponent(btnHistorial))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscarEstudiante)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarEstudiante)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarCurso)
                    .addComponent(txtBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCurso))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {

            int id
                    = Integer.parseInt(
                            txtId.getText().trim()
                    );

            int indiceEstudiante
                    = cmbEstudiante.getSelectedIndex();

            int indiceCurso
                    = cmbCurso.getSelectedIndex();

            if (indiceEstudiante == -1
                    || indiceCurso == -1) {

                JOptionPane.showMessageDialog(
                        this,
                        "Debe seleccionar estudiante y curso."
                );

                return;
            }

            Estudiante estudiante
                    = estudianteNegocio.obtenerTodos()
                            .get(indiceEstudiante);

            Curso curso
                    = cursoNegocio.obtenerTodos()
                            .get(indiceCurso);

            Matricula matricula
                    = new Matricula(
                            id,
                            estudiante,
                            curso
                    );

            matriculaNegocio.registrar(
                    matricula
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Matrícula registrada correctamente."
            );

            cargarTabla();

            limpiarCampos();

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage()
            );

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila
                = tblMatriculas.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una matrícula."
            );

            return;
        }

        Matricula matricula
                = matriculaNegocio.obtenerTodas()
                        .get(fila);

        matriculaNegocio.eliminar(
                matricula
        );

        JOptionPane.showMessageDialog(
                this,
                "Matrícula eliminada."
        );

        cargarTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo
                = (DefaultTableModel) tblMatriculas.getModel();

        modelo.setRowCount(0);

        for (Matricula m
                : matriculaNegocio.buscarPorEstudiante(
                        txtBuscarEstudiante.getText()
                )) {

            modelo.addRow(new Object[]{
                m.getId(),
                m.getEstudiante().getNombre(),
                m.getCurso().getNombre()

            });
        }
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed

    private void btnBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCursoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo
                = (DefaultTableModel) tblMatriculas.getModel();

        modelo.setRowCount(0);

        for (Matricula m
                : matriculaNegocio.buscarPorCurso(
                        txtBuscarCurso.getText()
                )) {

            modelo.addRow(new Object[]{
                m.getId(),
                m.getEstudiante().getNombre(),
                m.getCurso().getNombre()

            });
        }
    }//GEN-LAST:event_btnBuscarCursoActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // TODO add your handling code here:
        cargarCombos();

        cargarTabla();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        StringBuilder historial
                = new StringBuilder();

        for (String accion
                : matriculaNegocio.getHistorial()) {

            historial.append(accion)
                    .append("\n");

        }

        JOptionPane.showMessageDialog(
                this,
                historial.toString(),
                "Historial",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnHistorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JComboBox<String> cmbEstudiante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarCurso;
    private javax.swing.JLabel lblBuscarEstudiante;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblMatriculas;
    private javax.swing.JTextField txtBuscarCurso;
    private javax.swing.JTextField txtBuscarEstudiante;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
